import * as THREE from 'https://esm.sh/three@0.179.1';

const page=(location.pathname.split('/').pop()||'index.html').replace('.html','');
const scene=new THREE.Scene();scene.fog=new THREE.Fog(0x052c48,8,28);
const camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,80);camera.position.set(0,3.8,13);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight);renderer.setClearColor(0x031426);document.body.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xd8ffff,0x06351f,2.9));const sun=new THREE.DirectionalLight(0xffffff,2.1);sun.position.set(-4,8,7);scene.add(sun);
const root=new THREE.Group();scene.add(root);let links=[],state=load();
const color={blue:['#20d8ff','#035f9f'],orange:['#ffb129','#f06400'],green:['#68f29a','#08783e'],dark:['#0b3856','#04172b'],red:['#ff6d86','#8f1431']};
function tex(text,sub='',pair=color.dark,w=1024,h=256){const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,0,h);g.addColorStop(0,pair[0]);g.addColorStop(1,pair[1]);x.fillStyle=g;x.roundRect(0,0,w,h,48);x.fill();x.strokeStyle='rgba(255,255,255,.45)';x.lineWidth=10;x.stroke();x.fillStyle='white';x.textAlign='center';x.textBaseline='middle';x.font='900 64px system-ui';x.fillText(text,w/2,sub?h*.42:h/2);if(sub){x.fillStyle='rgba(235,255,255,.78)';x.font='700 34px system-ui';x.fillText(sub,w/2,h*.68)}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function plane(text,sub,x,y,w,h,pair,fn){const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:tex(text,sub,pair),transparent:true}));m.position.set(x,y,.55);m.userData.fn=fn;root.add(m);if(fn)links.push(m);return m}
function make(type,geo,col,scale,pos,rot=[0,0,0]){const m=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:col,roughness:.36,metalness:.06}));m.scale.set(...scale);m.position.set(...pos);m.rotation.set(...rot);return m}
function animal(p,i){const g=new THREE.Group(),c={Turtle:0x43c95c,Clownfish:0xff7a00,Seahorse:0xffbf3c,Jellyfish:0xc58cff,Dolphin:0x39bdf2,Octopus:0xb456ff,Shark:0x8fa5b8,Whale:0x3178d8,Stingray:0x746bff,Angelfish:0xff59ca}[p.type]||0x20d6ff;const add=(geo,col,sc,pos,rot)=>g.add(make(p.type,geo,col,sc,pos,rot));
 if(p.type==='Turtle'){add(new THREE.SphereGeometry(.55,32,20),0x26744a,[1.45,.42,1.05],[0,0,0]);add(new THREE.SphereGeometry(.23,16,12),c,[.9,.7,.7],[.85,.03,0]);for(const z of[-.55,.55])add(new THREE.SphereGeometry(.2,12,8),c,[1.2,.16,.46],[-.12,-.06,z])}
 else if(p.type==='Jellyfish'){add(new THREE.SphereGeometry(.55,32,16),c,[1.2,.58,1.2],[0,.18,0]);for(let k=0;k<9;k++)add(new THREE.CapsuleGeometry(.025,.9,4,8),c,[1,1,1],[-.48+k*.12,-.58,Math.sin(k)*.3],[0,0,Math.sin(k)*.25])}
 else if(p.type==='Octopus'){add(new THREE.SphereGeometry(.5,32,18),c,[1.1,1,1.1],[0,.18,0]);for(let k=0;k<8;k++)add(new THREE.CapsuleGeometry(.055,.75,5,8),c,[1,1,1],[Math.cos(k)*.35,-.5,Math.sin(k)*.35],[.7,0,k])}
 else if(p.type==='Stingray'){add(new THREE.CircleGeometry(.9,48),c,[1.55,.75,1],[0,0,0],[-Math.PI/2,0,0]);add(new THREE.ConeGeometry(.08,1.2,8),c,[1,1,1],[-.95,0,0],[0,0,Math.PI/2])}
 else if(p.type==='Seahorse'){for(let k=0;k<5;k++)add(new THREE.SphereGeometry(.2,20,12),c,[1.1-k*.08,1,1],[.18*Math.sin(k),.42-k*.2,0]);add(new THREE.ConeGeometry(.12,.55,16),c,[1,1,1],[.32,.38,0],[0,0,-Math.PI/2]);add(new THREE.TorusGeometry(.22,.035,8,24),c,[1,1,1],[-.08,-.62,0],[0,Math.PI/2,0])}
 else {const long=p.type==='Whale'?2.45:p.type==='Shark'?1.95:p.type==='Dolphin'?1.75:p.type==='Angelfish'?1.05:1.45;add(new THREE.SphereGeometry(.5,32,18),c,[long,.62,.52],[0,0,0]);add(new THREE.ConeGeometry(.28,.65,3),c,[1,1,1],[-long*.48,0,0],[0,0,Math.PI/2]);add(new THREE.ConeGeometry(.18,.55,3),c,[1,1,1],[.05,.45,0]);if(p.type==='Clownfish')for(const x of[-.25,.25])add(new THREE.BoxGeometry(.06,.72,.62),0xffffff,[1,1,1],[x,0,.01]);if(p.type==='Shark')add(new THREE.ConeGeometry(.22,.7,3),0xdbe9f2,[1,1,1],[.82,.02,0],[0,0,-Math.PI/2]);if(p.type==='Angelfish')add(new THREE.ConeGeometry(.36,.9,3),0xffd166,[1,1,1],[0,.36,0],[0,0,Math.PI])}
 add(new THREE.SphereGeometry(.055,12,8),0x061724,[1,1,1],[.55,.12,.34]);g.position.set(-5+((p.x||20)/100)*10,-1.6+((p.y||40)/100)*3.7,-1-i*.2);g.userData.phase=Math.random()*9;root.add(g);return g}
function background(){root.clear();links=[];root.add(make('sand',new THREE.CylinderGeometry(9,10,.45,64),0xd5a35f,[1,.5,.42],[0,-3.4,0]));for(let i=0;i<30;i++)root.add(make('plant',new THREE.CapsuleGeometry(.035,.7+Math.random()*1.6,4,8),i%3?0x26d07c:0x14a6a1,[1,1,1],[-7+Math.random()*14,-3,-3+Math.random()*4],[0,0,-.4+Math.random()*.8]));for(let i=0;i<44;i++){let b=make('bubble',new THREE.SphereGeometry(.03+Math.random()*.09,12,8),0xbff6ff,[1,1,1],[-7+Math.random()*14,-3+Math.random()*7,-3+Math.random()*4]);b.material.transparent=true;b.material.opacity=.45;b.userData.v=.01+Math.random()*.02;root.add(b)}}
function hud(){plane('OCEAN PETS','Level '+state.level+'   Pearls '+state.pearls,-4.6,3.35,3.9,.8,color.dark);plane('HOME','',-5.7,-3.45,1.2,.46,color.blue,()=>location.href='index.html');plane('PETS','',-4.35,-3.45,1.2,.46,color.blue,()=>location.href='pets.html');plane('TANKS','',-3,-3.45,1.2,.46,color.blue,()=>location.href='aquariums.html');plane('GAMES','',-1.65,-3.45,1.2,.46,color.green,()=>location.href='games.html');plane('DECOR','',-.3,-3.45,1.2,.46,color.blue,()=>location.href='decorations.html');plane('HATCH','',1.05,-3.45,1.2,.46,color.orange,()=>location.href='hatchery.html');plane('SETTINGS','',2.55,-3.45,1.45,.46,color.dark,()=>location.href='settings.html')}
function renderPage(){background();hud();const active=state.aquariums[state.activeAquarium]||state.aquariums[0];plane(active.name,active.theme,0,2.65,4.3,.7,color.dark);state.pets.forEach(animal);if(page==='index'){plane('START AQUARIUM','Open your active Three.js tank',0,1.15,4.6,.82,color.orange,()=>location.href='aquariums.html');plane('MY PETS','Feed, rename and level animals',0,.1,4.6,.82,color.blue,()=>location.href='pets.html');plane('PLAY GAMES','Earn pearls and XP',0,-.95,4.6,.82,color.green,()=>location.href='games.html')}
else if(page==='pets'){state.pets.slice(0,5).forEach((p,i)=>plane(p.name,p.type+' L'+p.level+' H'+Math.round(p.hunger)+' E'+Math.round(p.energy),0,1.65-i*.7,5.2,.52,color.dark,()=>{p.hunger=Math.min(100,p.hunger+25);p.happiness=Math.min(100,p.happiness+12);state.pearls=Math.max(0,state.pearls-5);save(state);renderPage()}));plane('ADOPT UNLOCKED PET','Cost 50 pearls',0,-2.15,4.6,.62,color.green,()=>{if(state.pearls>=50){state.pearls-=50;state.pets.push(pet(unlockedPets(state).at(-1)[0],'New Pet'));save(state);renderPage()}})}
else if(page==='aquariums'){state.aquariums.forEach((a,i)=>plane((i===state.activeAquarium?'ACTIVE ':'')+a.name,a.theme,0,1.7-i*.72,5.2,.56,i===state.activeAquarium?color.green:color.dark,()=>{state.activeAquarium=i;save(state);renderPage()}));plane('NEW AQUARIUM','Adds a themed tank',0,-2.45,4.8,.62,color.orange,()=>{state.aquariums.push({id:id(),name:'Aquarium '+(state.aquariums.length+1),theme:THEMES[state.aquariums.length%THEMES.length],decorations:[]});save(state);renderPage()})}
else if(page==='games'){[['TURTLE MAZE','turtle-maze.html'],['PEARL RUSH','pearl-rush.html'],['BUBBLE POP','bubble-pop.html'],['FISH CATCH','fish-catch.html'],['REEF RESCUE','reef-rescue.html']].forEach((g,i)=>plane(g[0],'Best '+(state.scores[g[0].replace(/\b\w/g,m=>m)]||0),0,1.7-i*.72,5.2,.56,color.green,()=>location.href=g[1]))}
else if(page==='decorations'){unlockedDecs(state).slice(0,6).forEach((d,i)=>plane(d[0],'Cost '+d[3]+' pearls',0,1.65-i*.65,5.2,.52,color.dark,()=>{if(state.pearls>=d[3]){state.pearls-=d[3];active.decorations.push(d[0]);save(state);renderPage()}}))}
else if(page==='hatchery'){[['COMMON EGG',60,1],['RARE EGG',160,5],['LEGENDARY EGG',360,10]].forEach((e,i)=>plane(e[0],'Hatch a saved pet',0,1.3-i*.9,5,.65,color.orange,()=>{if(state.pearls>=e[1]){state.pearls-=e[1];let p=unlockedPets(state).at(-1);state.pets.push(pet(p[0],p[0]));save(state);renderPage()}}))}
else if(page==='settings'){plane('RESET SAVE','Start over',0,.8,4.5,.7,color.red,()=>{localStorage.removeItem(OP_KEY);state=load();renderPage()});plane('PARTICLES '+(state.settings.particles?'ON':'OFF'),'Toggle visual bubbles',0,-.1,4.5,.7,color.blue,()=>{state.settings.particles=!state.settings.particles;save(state);renderPage()})}
else if(page.includes('maze')||page.includes('rush')||page.includes('pop')||page.includes('catch')||page.includes('rescue')){let title=document.title.toUpperCase();plane(title,'Tap targets to score. Awards save instantly.',0,1.5,5.4,.7,color.green);for(let i=0;i<10;i++)plane(['PEARL','BUBBLE','FISH','TRASH','STAR'][i%5],'+10',-4+(i%5)*2,0.4-Math.floor(i/5)*1.1,1.4,.48,color.blue,()=>{award(document.title,10,8,(state.scores[document.title]||0)+10);state=load();renderPage()})}}
renderPage();
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();addEventListener('pointerdown',ev=>{pointer.x=ev.clientX/innerWidth*2-1;pointer.y=-(ev.clientY/innerHeight)*2+1;ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(links)[0];if(hit)hit.object.userData.fn()});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
let time=0;renderer.setAnimationLoop(()=>{time+=.016;root.children.forEach(o=>{if(o.userData.v){o.position.y+=o.userData.v;if(o.position.y>4)o.position.y=-3.2}if(o.userData.phase){o.position.x+=Math.sin(time+o.userData.phase)*.004;o.rotation.y=Math.sin(time*.8+o.userData.phase)*.28}});renderer.render(scene,camera)});
