const OP_KEY='oceanPetsSaveV1';
const PETS=[['Turtle','🐢',1],['Clownfish','🐠',1],['Seahorse','🌊',2],['Jellyfish','🪼',3],['Dolphin','🐬',5],['Octopus','🐙',7],['Shark','🦈',9],['Whale','🐋',12],['Stingray','🔷',15],['Angelfish','🐟',18]];
const THEMES=['Tropical Reef','Deep Ocean','Blue Lagoon','Kelp Forest','Sunken Kingdom'];
const DECS=[['Coral','🪸',1,40],['Rocks','🪨',1,25],['Seaweed','🌿',2,35],['Bubble Machine','🫧',3,80],['Treasure Chest','🧰',5,120],['Statue','🗿',7,160],['Sunken Ship','⛵',10,260],['Castle','🏰',14,380]];
const FOODS={SeaGrass:{icon:'🌿',cost:4,hunger:18,happiness:3,energy:2},Shrimp:{icon:'🦐',cost:9,hunger:28,happiness:6,energy:3},SmallFish:{icon:'🐟',cost:14,hunger:38,happiness:5,energy:6},Crab:{icon:'🦀',cost:18,hunger:32,happiness:12,energy:6},PremiumTreat:{icon:'🍬',cost:35,hunger:55,happiness:25,energy:18}};
function starter(){return {pearls:120,xp:0,level:1,settings:{sound:true,particles:true},scores:{},pets:[pet('Turtle','Shelly'),pet('Clownfish','Bubbles')],aquariums:[{id:id(),name:'My Reef',theme:'Tropical Reef',decorations:['Coral','Rocks']}],activeAquarium:0,last:Date.now()}}
function id(){return Math.random().toString(36).slice(2,10)}
function pet(type,name){return {id:id(),type,name:name||type,hunger:82,happiness:80,energy:76,level:1,xp:0,age:0,x:20+Math.random()*55,y:20+Math.random()*45,vx:Math.random()>.5?1:-1,vy:Math.random()>.5?1:-1}}
function load(){let s;try{s=JSON.parse(localStorage.getItem(OP_KEY))}catch(e){};s=s||starter();tick(s);save(s);return s}
function save(s){localStorage.setItem(OP_KEY,JSON.stringify(s));window.dispatchEvent(new Event('op-save'))}
function xp(s,n){s.xp+=n;while(s.xp>=s.level*100){s.xp-=s.level*100;s.level++;s.pearls+=25+s.level*5}save(s)}
function tick(s){const hrs=Math.min(24,(Date.now()-(s.last||Date.now()))/36e5);s.pets.forEach(p=>{p.age+=(hrs/24);p.hunger=Math.max(0,p.hunger-hrs*3);p.happiness=Math.max(0,p.happiness-hrs*2);p.energy=Math.max(0,p.energy-hrs*1.5)});s.last=Date.now()}
function unlockedPets(s){return PETS.filter(p=>s.level>=p[2])}function unlockedDecs(s){return DECS.filter(d=>s.level>=d[2])}
function nav(){return '<nav class="nav">'+[['🏠','Home','index.html'],['🐾','Pets','pets.html'],['🏝️','Tanks','aquariums.html'],['🎮','Games','games.html'],['🪸','Decor','decorations.html'],['🥚','Hatch','hatchery.html'],['⚙️','Settings','settings.html']].map(a=>`<a href="${a[2]}">${a[0]}<br>${a[1]}</a>`).join('')+'</nav>'}
function shell(title){const s=load();document.body.insertAdjacentHTML('afterbegin',`<div class="app"><header class="top"><div class="brand"><div class="logo">🐚</div><div><h1>${title}</h1><div class="muted">Ocean Pets • Level ${s.level}</div></div></div><div class="stats"><span class="pill">🦪 ${s.pearls}</span><span class="pill">⭐ ${s.xp}/${s.level*100}</span></div></header><main id="main"></main></div>${nav()}`);bubbles()}
function bubbles(){if(load().settings.particles===false)return;setInterval(()=>{const b=document.createElement('i');b.className='bubble';const z=8+Math.random()*30;b.style.cssText=`left:${Math.random()*100}vw;bottom:-40px;width:${z}px;height:${z}px;animation-duration:${5+Math.random()*7}s`;document.body.appendChild(b);setTimeout(()=>b.remove(),12000)},500)}
function aquarium(el){const s=load(),a=s.aquariums[s.activeAquarium]||s.aquariums[0];el.className='hero';el.innerHTML=`<div class="sand"></div><div class="muted" style="position:absolute;left:16px;top:12px">${a.name} • ${a.theme}</div>`+(a.decorations||[]).map((d,i)=>`<span class="sprite" style="left:${8+i*12%78}%;bottom:${22+(i%3)*18}px">${(DECS.find(x=>x[0]==d)||[])[1]||'🪸'}</span>`).join('');s.pets.forEach(p=>{let e=document.createElement('span');e.className='pet';e.textContent=(PETS.find(x=>x[0]==p.type)||[])[1]||'🐠';el.appendChild(e);setInterval(()=>{p.x+=p.vx*(.8+Math.random()*1.8);p.y+=p.vy*(.6+Math.random()*1.2);if(p.x<2||p.x>88)p.vx*=-1;if(p.y<10||p.y>70)p.vy*=-1;p.x=Math.max(2,Math.min(88,p.x));p.y=Math.max(10,Math.min(70,p.y));e.style.left=p.x+'%';e.style.top=p.y+'%';e.style.transform=`scaleX(${p.vx>0?1:-1}) rotate(${p.vy*4}deg)`},700)})}
function toast(t){let m=document.createElement('div');m.className='pill';m.style.cssText='position:fixed;z-index:20;left:50%;bottom:90px;transform:translateX(-50%)';m.textContent=t;document.body.appendChild(m);setTimeout(()=>m.remove(),1800)}
function award(game,pearls,xpv,score){const s=load();s.pearls+=pearls;s.scores[game]=Math.max(s.scores[game]||0,score);xp(s,xpv);toast(`+${pearls} pearls +${xpv} XP`)}
if('serviceWorker' in navigator) addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
