const OP_KEY='oceanPetsSaveV1';
const PETS=[['Turtle','Turtle',1],['Clownfish','Clownfish',1],['Seahorse','Seahorse',2],['Jellyfish','Jellyfish',3],['Dolphin','Dolphin',5],['Octopus','Octopus',7],['Shark','Shark',9],['Whale','Whale',12],['Stingray','Stingray',15],['Angelfish','Angelfish',18]];
const THEMES=['Tropical Reef','Deep Ocean','Blue Lagoon','Kelp Forest','Sunken Kingdom'];
const DECS=[['Coral','Coral',1,40],['Rocks','Rocks',1,25],['Seaweed','Seaweed',2,35],['Bubble Machine','Bubbles',3,80],['Treasure Chest','Chest',5,120],['Statue','Statue',7,160],['Sunken Ship','Ship',10,260],['Castle','Castle',14,380]];
const FOODS={SeaGrass:{icon:'',cost:4,hunger:18,happiness:3,energy:2},Shrimp:{icon:'',cost:9,hunger:28,happiness:6,energy:3},SmallFish:{icon:'',cost:14,hunger:38,happiness:5,energy:6},Crab:{icon:'',cost:18,hunger:32,happiness:12,energy:6},PremiumTreat:{icon:'',cost:35,hunger:55,happiness:25,energy:18}};
function starter(){return {pearls:120,xp:0,level:1,settings:{sound:true,particles:true},scores:{},pets:[pet('Turtle','Shelly'),pet('Clownfish','Bubbles')],aquariums:[{id:id(),name:'My Reef',theme:'Tropical Reef',decorations:['Coral','Rocks']}],activeAquarium:0,last:Date.now()}}
function id(){return Math.random().toString(36).slice(2,10)}
function pet(type,name){return {id:id(),type,name:name||type,hunger:82,happiness:80,energy:76,level:1,xp:0,age:0,x:20+Math.random()*55,y:20+Math.random()*45,vx:Math.random()>.5?1:-1,vy:Math.random()>.5?1:-1}}
function load(){let s;try{s=JSON.parse(localStorage.getItem(OP_KEY))}catch(e){};s=s||starter();tick(s);save(s);return s}
function save(s){localStorage.setItem(OP_KEY,JSON.stringify(s));window.dispatchEvent(new Event('op-save'))}
function xp(s,n){s.xp+=n;while(s.xp>=s.level*100){s.xp-=s.level*100;s.level++;s.pearls+=25+s.level*5}save(s)}
function tick(s){const hrs=Math.min(24,(Date.now()-(s.last||Date.now()))/36e5);s.pets.forEach(p=>{p.age+=(hrs/24);p.hunger=Math.max(0,p.hunger-hrs*3);p.happiness=Math.max(0,p.happiness-hrs*2);p.energy=Math.max(0,p.energy-hrs*1.5)});s.last=Date.now()}
function unlockedPets(s){return PETS.filter(p=>s.level>=p[2])}function unlockedDecs(s){return DECS.filter(d=>s.level>=d[2])}
function nav(){return '<nav class="nav">'+[['Home','Home','index.html'],['Pets','Pets','pets.html'],['Tanks','Tanks','aquariums.html'],['Games','Games','games.html'],['Decor','Decor','decorations.html'],['Hatch','Hatch','hatchery.html'],['Settings','Settings','settings.html']].map(a=>`<a href="${a[2]}">${a[1]}</a>`).join('')+'</nav>'}
function shell(title){const s=load();document.body.insertAdjacentHTML('afterbegin',`<div class="caustics"></div><div class="app"><header class="top"><div class="brand"><div class="logo">OP</div><div><h1>${title}</h1><div class="muted">Ocean Pets - Level ${s.level}</div></div></div><div class="stats"><span class="pill">Pearls ${s.pearls}</span><span class="pill">XP ${s.xp}/${s.level*100}</span></div></header><main id="main"></main></div>${nav()}`);bubbles()}
function bubbles(){if(load().settings.particles===false)return;setInterval(()=>{const b=document.createElement('i');b.className='bubble';const z=8+Math.random()*30;b.style.cssText=`left:${Math.random()*100}vw;bottom:-40px;width:${z}px;height:${z}px;animation-duration:${5+Math.random()*7}s`;document.body.appendChild(b);setTimeout(()=>b.remove(),12000)},500)}
function petColor(type){return {Turtle:['linear-gradient(145deg,#86f36f,#0a6a48)','linear-gradient(145deg,#6bd95e,#0a6a48)'],Clownfish:['linear-gradient(145deg,#fff,#ff8a00 38%,#ff4f00 62%,#fff 70%)','#ff7a00'],Seahorse:['linear-gradient(145deg,#ffd36b,#ff7a00)','#ffb100'],Jellyfish:['linear-gradient(145deg,#ffffff,#ce8cff 55%,#7f5bff)','rgba(206,140,255,.7)'],Dolphin:['linear-gradient(145deg,#b7f5ff,#3498db 55%,#1761a0)','#48c7ff'],Octopus:['linear-gradient(145deg,#ff9bd4,#9b4dff 55%,#4b1c8a)','#b04dff'],Shark:['linear-gradient(145deg,#d6f5ff,#607d8b 55%,#263746)','#78909c'],Whale:['linear-gradient(145deg,#b7dcff,#275ea8 55%,#123260)','#2f6fc1'],Stingray:['linear-gradient(145deg,#d8ccff,#635bff 55%,#25226e)','#756dff'],Angelfish:['linear-gradient(145deg,#fff7a8,#ff4bd8 55%,#6f2cff)','#ff4bd8']}[type]||['linear-gradient(145deg,#fff,#19d6ff)','#19d6ff']}
function aquarium(el){const s=load(),a=s.aquariums[s.activeAquarium]||s.aquariums[0];el.className='hero';el.innerHTML=`<div class="sand"></div><div class="pill" style="position:absolute;left:14px;top:14px;z-index:3">${a.name} - ${a.theme}</div>`+(a.decorations||[]).map((d,i)=>`<span class="decor3d" style="left:${6+i*12%82}%;bottom:${54+(i%3)*18}px">${(DECS.find(x=>x[0]==d)||[])[1]||'Decor'}</span>`).join('')+Array.from({length:14},(_,i)=>`<i class="plant" style="left:${(i*11+7)%94}%;height:${45+(i%5)*18}px;animation-delay:-${i*.3}s"></i>`).join('');s.pets.forEach(p=>{let c=petColor(p.type),e=document.createElement('div');e.className='pet3d';e.style.setProperty('--body',c[0]);e.style.setProperty('--fin',c[1]);e.innerHTML=`<span class="tail"></span><span class="fin"></span><span class="pet-label">${p.name} - Lv ${p.level}</span>`;el.appendChild(e);setInterval(()=>{p.x+=p.vx*(1.2+Math.random()*2.4);p.y+=p.vy*(.8+Math.random()*1.7);if(p.x<1||p.x>88)p.vx*=-1;if(p.y<12||p.y>72)p.vy*=-1;p.x=Math.max(1,Math.min(88,p.x));p.y=Math.max(12,Math.min(72,p.y));e.style.left=p.x+'%';e.style.top=p.y+'%';e.style.transform=`scaleX(${p.vx>0?1:-1}) translateZ(0) rotate(${p.vy*3}deg)`},650)}); import('./ocean3d.js').then(m=>m.mountAquarium(el,s,a)).catch(()=>{})}
function toast(t){let m=document.createElement('div');m.className='pill';m.style.cssText='position:fixed;z-index:20;left:50%;bottom:90px;transform:translateX(-50%)';m.textContent=t;document.body.appendChild(m);setTimeout(()=>m.remove(),1800)}
function award(game,pearls,xpv,score){const s=load();s.pearls+=pearls;s.scores[game]=Math.max(s.scores[game]||0,score);xp(s,xpv);toast(`+${pearls} pearls +${xpv} XP`)}
if('serviceWorker' in navigator) addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
